graph [
  directed 1
  node [ id 0 label "Glucose" displayName "Glucose" schemaClass "SmallMolecule" category "substrate" ]
  node [ id 1 label "Hexokinase" displayName "Hexokinase" schemaClass "EntityWithAccessionedSequence" referenceType "ReferenceGeneProduct" category "enzyme" ]
  node [ id 2 label "ATP" displayName "ATP" schemaClass "SmallMolecule" category "cofactor" ]
  node [ id 3 label "G6P" displayName "Glucose-6-phosphate" schemaClass "SmallMolecule" category "intermediate" ]
  node [ id 4 label "ADP" displayName "ADP" schemaClass "SmallMolecule" category "cofactor" ]
  node [ id 5 label "HexokinaseRxn" displayName "Hexokinase reaction" schemaClass "Reaction" category "reaction" ]
  node [ id 6 label "PGI" displayName "Phosphoglucose isomerase" schemaClass "EntityWithAccessionedSequence" referenceType "ReferenceGeneProduct" category "enzyme" ]
  node [ id 7 label "F6P" displayName "Fructose-6-phosphate" schemaClass "SmallMolecule" category "intermediate" ]
  node [ id 8 label "PGIRxn" displayName "Phosphoglucose isomerase reaction" schemaClass "Reaction" category "reaction" ]
  node [ id 9 label "PFK1" displayName "Phosphofructokinase 1" schemaClass "EntityWithAccessionedSequence" referenceType "ReferenceGeneProduct" category "enzyme" ]
  node [ id 10 label "F16BP" displayName "Fructose-1,6-bisphosphate" schemaClass "SmallMolecule" category "intermediate" ]
  node [ id 11 label "PFK1Rxn" displayName "PFK1 reaction" schemaClass "Reaction" category "reaction" ]
  node [ id 12 label "Aldolase" displayName "Aldolase" schemaClass "EntityWithAccessionedSequence" referenceType "ReferenceGeneProduct" category "enzyme" ]
  node [ id 13 label "DHAP" displayName "Dihydroxyacetone phosphate" schemaClass "SmallMolecule" category "intermediate" ]
  node [ id 14 label "G3P" displayName "Glyceraldehyde-3-phosphate" schemaClass "SmallMolecule" category "intermediate" ]
  node [ id 15 label "AldolaseRxn" displayName "Aldolase reaction" schemaClass "Reaction" category "reaction" ]
  node [ id 16 label "TPI" displayName "Triose phosphate isomerase" schemaClass "EntityWithAccessionedSequence" referenceType "ReferenceGeneProduct" category "enzyme" ]
  node [ id 17 label "TPIRxn" displayName "TPI reaction" schemaClass "Reaction" category "reaction" ]
  node [ id 18 label "GlycolysisPath" displayName "Upper glycolysis pathway" schemaClass "Pathway" category "pathway" ]
  node [ id 19 label "InsulinSig" displayName "Insulin signalling upstream" schemaClass "BlackBoxEvent" category "upstream" ]
  node [ id 20 label "CancerReg" displayName "Warburg effect regulator" schemaClass "PositiveGeneExpressionRegulation" category "regulation" ]
  node [ id 21 label "HexokinaseGene" displayName "HK2 gene" schemaClass "ReferenceGeneProduct" category "gene" ]
  node [ id 22 label "PFK1Gene" displayName "PFKM gene" schemaClass "ReferenceGeneProduct" category "gene" ]
  node [ id 23 label "HexokinaseCpx" displayName "Hexokinase:Glucose complex" schemaClass "Complex" category "complex" ]
  node [ id 24 label "PFK1Cpx" displayName "PFK1 activated complex" schemaClass "Complex" category "complex" ]

  edge [ source 0 target 5 ]
  edge [ source 2 target 5 ]
  edge [ source 1 target 5 ]
  edge [ source 5 target 3 ]
  edge [ source 5 target 4 ]
  edge [ source 3 target 8 ]
  edge [ source 6 target 8 ]
  edge [ source 8 target 7 ]
  edge [ source 7 target 11 ]
  edge [ source 9 target 11 ]
  edge [ source 2 target 11 ]
  edge [ source 11 target 10 ]
  edge [ source 11 target 4 ]
  edge [ source 10 target 15 ]
  edge [ source 12 target 15 ]
  edge [ source 15 target 13 ]
  edge [ source 15 target 14 ]
  edge [ source 13 target 17 ]
  edge [ source 16 target 17 ]
  edge [ source 17 target 14 ]
  edge [ source 18 target 5 ]
  edge [ source 18 target 8 ]
  edge [ source 18 target 11 ]
  edge [ source 18 target 15 ]
  edge [ source 18 target 17 ]
  edge [ source 19 target 9 ]
  edge [ source 20 target 1 ]
  edge [ source 20 target 9 ]
  edge [ source 21 target 1 ]
  edge [ source 22 target 9 ]
  edge [ source 1 target 23 ]
  edge [ source 0 target 23 ]
  edge [ source 9 target 24 ]
]
