// ============================================================================
// BioClaw Scientific Report Template — Style Library
// Import this file to get all styling and component functions.
// Usage: #import "scientific_report.typ": *
// ============================================================================

// ── Color Palette ──
#let primary   = rgb("#1a5276")
#let accent    = rgb("#148f77")
#let light-bg  = rgb("#f0f4f5")
#let note-bg   = rgb("#d1ecf1")
#let note-bdr  = rgb("#17a2b8")
#let warn-bg   = rgb("#fff3cd")
#let warn-bdr  = rgb("#ffc107")
#let ok-bg     = rgb("#d4edda")
#let ok-bdr    = rgb("#28a745")
#let err-bg    = rgb("#f8d7da")
#let err-bdr   = rgb("#dc3545")
#let muted     = rgb("#6c757d")
#let border-c  = rgb("#dee2e6")

// ── Callout Box ──
#let callout(body, title: "Note", kind: "note") = {
  let (bg, bdr) = if kind == "warning" { (warn-bg, warn-bdr) }
    else if kind == "success" { (ok-bg, ok-bdr) }
    else if kind == "danger" { (err-bg, err-bdr) }
    else { (note-bg, note-bdr) }
  block(
    width: 100%, fill: bg,
    stroke: (left: 4pt + bdr),
    radius: (right: 3pt),
    inset: (x: 14pt, y: 10pt),
    breakable: true,
  )[
    #if title != none {
      text(weight: "bold", size: 9.5pt, fill: bdr.darken(25%))[#title]
      linebreak()
    }
    #set text(size: 9.5pt)
    #body
  ]
}

// ── Styled Data Table ──
// NOTE: we avoid wrapping in figure() for large tables because Typst treats
// the entire figure as an atomic block. If it doesn't fit on the current page
// it gets pushed to the next page, leaving a blank page.  Instead we output
// the table directly (which IS breakable across pages) and add an italic
// caption line below it manually.
#let data-table(headers, rows, caption-text: none) = {
  let header-cells = headers.map(h =>
    table.cell(fill: primary)[
      #text(fill: white, weight: "bold", size: 8.5pt)[#upper(h)]
    ]
  )
  let body-cells = rows.enumerate().map(((i, row)) => {
    let bg = if calc.rem(i, 2) == 0 { white } else { light-bg }
    row.map(cell =>
      table.cell(fill: bg)[#text(size: 9pt)[#cell]]
    )
  }).flatten()

  table(
    columns: headers.len(),
    stroke: 0.5pt + border-c,
    inset: (x: 10pt, y: 6pt),
    ..header-cells,
    ..body-cells,
  )
  if caption-text != none {
    v(4pt)
    align(center)[
      #text(size: 9pt, style: "italic", fill: rgb("#555555"))[#caption-text]
    ]
  }
}

// ── Key-Value Metadata Block ──
#let metadata-block(pairs) = {
  block(width: 100%, stroke: 0.5pt + border-c, radius: 3pt, inset: 0pt, breakable: true)[
    #for (i, (key, value)) in pairs.enumerate() {
      let bg = if calc.rem(i, 2) == 0 { white } else { light-bg }
      block(width: 100%, fill: bg, inset: (x: 14pt, y: 8pt))[
        #grid(
          columns: (35%, 65%),
          text(weight: "bold", fill: accent, size: 9.5pt)[#key],
          text(size: 9.5pt)[#value],
        )
      ]
    }
  ]
}

// ── Metric Cards ──
#let metric-cards(metrics) = {
  let cards = metrics.map(m => {
    box(
      width: 1fr,
      stroke: (top: 3pt + accent, rest: 0.5pt + border-c),
      radius: 3pt,
      inset: (x: 12pt, y: 10pt),
      fill: light-bg,
    )[
      #align(center)[
        #text(size: 18pt, weight: "bold", fill: primary)[#m.value]
        #linebreak()
        #text(size: 7.5pt, fill: muted, weight: "regular")[#upper(m.label)]
      ]
    ]
  })
  grid(columns: cards.len(), column-gutter: 10pt, ..cards)
}

// ── Report Setup Function ──
#let report-setup(
  title: "Analysis Report",
  subtitle: "",
  date: "",
  author: "BioClaw",
  project: "",
  confidential: "Confidential",
  header-left: none,
  body,
) = {
  let hl = if header-left != none { header-left } else { title }

  // Page setup
  set page(
    paper: "a4",
    margin: (top: 2.45cm, bottom: 2.2cm, left: 2.0cm, right: 2.0cm),
    header: context {
      if counter(page).get().first() > 1 {
        set text(7.5pt, fill: muted)
        grid(columns: (1fr, 1fr), align: (left, right),
          [#hl], [#date | #confidential])
        v(2pt)
        line(length: 100%, stroke: 0.4pt + border-c)
      }
    },
    footer: context {
      set text(7.5pt, fill: muted)
      line(length: 100%, stroke: 0.4pt + border-c)
      v(3pt)
      grid(columns: (1fr, 1fr), align: (left, right),
        [Generated by #author],
        [Page #counter(page).display("1 of 1", both: true)])
    },
  )

  // Typography
  set text(
    font: ("Liberation Sans", "Arial", "Noto Sans", "DejaVu Sans"),
    size: 9.8pt, fill: rgb("#333333"),
  )
  set par(justify: true, leading: 0.66em, first-line-indent: 0pt)

  // Heading styles — compact spacing to avoid wasted whitespace
  show heading.where(level: 1): it => {
    v(10pt)
    block(width: 100%, fill: primary, radius: 3pt,
          inset: (x: 14pt, y: 8pt), breakable: false)[
      #text(fill: white, weight: "bold", size: 13pt)[#it.body]
    ]
    v(4pt)
  }

  show heading.where(level: 2): it => {
    v(8pt)
    block(width: 100%)[
      #text(fill: accent, weight: "bold", size: 11.5pt)[#it.body]
      #v(-2pt)
      #line(length: 100%, stroke: 1.5pt + accent.lighten(50%))
    ]
    v(3pt)
  }

  show heading.where(level: 3): it => {
    v(6pt)
    text(fill: primary, weight: "bold", size: 10.5pt)[#it.body]
    v(2pt)
  }

  // Figure captions
  show figure.caption: it => {
    set text(size: 9pt, style: "italic", fill: rgb("#555555"))
    it
  }

  // Links
  show link: it => text(fill: accent)[#it]

  // Title page
  v(1.65cm)
  align(left)[
    #text(size: 23pt, weight: "bold", fill: primary)[#title]
    #v(4pt)
    #if subtitle != "" {
      text(size: 11.5pt, fill: accent)[#subtitle]
      v(4pt)
    }
  ]
  v(6pt)
  line(length: 42%, stroke: 1.8pt + primary)
  v(12pt)

  set text(size: 9.5pt)
  if date != "" [Date: #date \ ]
  if author != "" [Analyst: #author \ ]
  if project != "" [Project: #project]

  v(16pt)

  // Body content
  body
}
